### ISSUE TITLE
Cannot build and preview my content in local

### ISSUE THREAD

**Issue by TRASERDanielGorski** [MicrosoftDocs/dynamics365smb-docs-pr.de-de#1]
Dear all,

by running the script ".openpublishing.build.ps1" on root folder I get the following error:

{"source":"C:\\Temp\\dynamics365smb-docs-pr.de-de-live\\.optemp\\packages\\opbuild.scripts.1.72.0\\tools\\build.entrypoint.ps1","log_item_type":"System","line":388,"message_severity":"Error","message":"Error happened in build.entrypoint.ps1. Please retry building your content. If the issue still happens, open a ticket in http://SiteHelp and include the following error message for our team to troubleshoot: ","date_time":"2019-04-02 10:13:35.888313Z","file":""}

I would appreciate it to get any advice.

Best regards,
Daniel

**Comment by dgoldsch** [comment]
It sounds like you are running DocFx from the root of your clone of the repo. You should change the path to run in the business-central folder. That way, the tool won't try to process the files that are there for the purposes of the Docs.microsoft.com site. For more information, see https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/help/contributor-guide#building-html-files 

Best regards,
Daniel
