### ISSUE TITLE
Incorrect link in the German version to the shortcuts

### ISSUE THREAD

**Issue by FSharpCSharp** [MicrosoftDocs/dynamics365smb-docs-pr.de-de#2]
In the German version a link to an English shortcut document is linked. This is of course stupid, although the translated version is stored correctly in this repository.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 839e7a63-b074-a7b7-0ee5-b9cea4313de0
* Version Independent ID: 545efe23-da43-c929-3edc-c63f52849cfd
* Content: [PC-Tastenkombinationskurzübersicht Referenz - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/keyboard-shortcuts-cheatsheet)
* Content Source: [business-central/keyboard-shortcuts-cheatsheet.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/keyboard-shortcuts-cheatsheet.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! This has been corrected by our translation team.
